### ISSUE TITLE
Would this work to secure a WebAPI which is called from a Mobile App?

### ISSUE THREAD

**Issue by KlausLoeffelmann** [Azure-Samples/active-directory-dotnet-native-aspnet5#13]
Question:
I need to secure a WebAPI with Azure AD _and_ with Microsoft Accounts using Microsoft.Identity.Client which I'm calling exclusively from a Mobile App or a Windows Desktop App.

Would this work sample work in that scenario as well?

**Comment by jmprieur** [comment]
Hello @KlausLoeffelmann you'd need to use MSAL.Net indeed, but the V2 endpoint does not support yet officially calling a 3rd party web API (other than the Microsoft Graph). This is coming, though.

**Comment by KlausLoeffelmann** [comment]
Thanks Jean-Marc for that info!

Some additional questions, though, if you don't mind and got the time:

- "Officially" kind of implies (hopefully! :-) ), there might be already an improvised, non/tested way to do this. If that's true, could you point us in the right direction, how we could achieve this, anyway? Would it possible somehow to modify this example in a way?
- Can you disclose any rough schedule; if there is a chance to get that feature before the MVP Summit starts (we can lead the reasons behind this question gladly in an offline conversation - it's klaus at Loeffelmann dot de.)
- Are there any alternatives you would know of we could use to secure a .NET Core WebAPI backend inside an UWP or Xamarin.Forms App with either an MSA or and AAD Account? (I only know of the mobile apps client, which unfortunately does not support .NET Core, yet).

Thanks so much for your support!

Klaus Löffelmann
(Microsoft VS and DevTech MVP)

**Comment by KathleenDollard** [comment]
@jmprieur Hello!

I just wanted to let you know that I'm a PM on .NET CLI/SDK these days, so I'm also interested in understanding the best security story for this combination. 

Kathleen

**Comment by jmprieur** [comment]
We have a .Net core sample on the AAD V1 endpoint: Desktop calling a Web API: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore 
We need to update it to use the AAD V2 endpoint (with MSAL). if you want to give it a try, you could leverage https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-windesktop which shows how to call the Graph from a V2 Desktop app.
