### ISSUE TITLE
WWW-Authenticate: Bearer error="invalid_token"

### ISSUE THREAD

**Issue by Sacratees** [Azure-Samples/active-directory-dotnet-native-aspnet5#20]
I have followed the active-directory-dotnet-native-aspnetcore sample. I am getting exception in one of the server like as below.

WWW-Authenticate: Bearer error="invalid_token", error_description="The signature key was not found"

The full trace info as below

Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match keys: 
kid: '[PII is hidden]', 
token: '[PII is hidden]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

Any idea on this issue?

**Comment by jmprieur** [comment]
@Sacratees : can you please explain your configuration:
- what do you call?
- did you change the code? the configuration?
- do you use the right token for the right Web API?

**Comment by Sacratees** [comment]
It was the issue from my side
  options.Authority = $"{_azureOptions.Instance}{_azureOptions.TenantId}";       
I have configured incorrect value for azureOptions.Instance. After updating the proper value, it worked  fine.

**Comment by shamiullahms** [comment]
Using the same active-directory-dotnet-native-aspnetcore sample, when I make call from Postman to API... Getting "500 Internal Server Error" any reason why?
