### ISSUE TITLE
AADSTS7000218: The request body must contain the following parameter: 

### ISSUE THREAD

**Issue by moudgilz** [Azure-Samples/active-directory-dotnet-native-aspnet5#22]
while entered the credential i have got below exception.

AADSTS7000218: The request body must contain the following parameter: 
'client_assertion' or ''client_secret'
trace ID: 34343hfdjueirerieurieufcndjnd*****
correlation Id: hf8urj48ufjh48fhrf4u9jcijf***: 
Exception: Response status code does not indicate success 401 (unauthorized)

The steps i have already done: 

I have given the permission to TodoListClient of Microsoft graph
beside given permission of TodoListService .
Manifest property **allowPublicClient": true,**  of TodoListClient 

Now stuck what left to do

**Comment by jmprieur** [comment]
@moudgilz:
- what app gets this exception? is it the TodoListClient? or the TodoListService? (I'm assuming the TodoListClient)
- can you provide detailed repro-steps? did you register the apps manually or use the app registration scripts?

**Comment by moudgilz** [comment]
Hi jmprieur,

- Yes i am getting this issue on TodoListClient application.
-  I have registered the app manually.
I have not deployed TodoListService  yet.
I have followed till **Step 4: Run the sample**

![image](https://user-images.githubusercontent.com/27800254/64000951-6a0cdd80-cb24-11e9-825f-3e6f1c355784.png)

**Comment by jmprieur** [comment]
@moudgilz 
there is a newer version of this sample: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2.
Do you mind using that one instead?
(this one has instructions for the older portal (now deprecated) and will be archived.

**Comment by moudgilz** [comment]
@jmprieur :- THANKS FOR HELP
