### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by shamiullahms** [Azure-Samples/active-directory-dotnet-native-aspnet5#23]
Cloned the "active-directory-dotnet-native-aspnetcore sample" setup App registration as per instruction. When I try to call todolist from Postman, I am getting no result with Status: 500 Internal Server Error. Any idea on this issue?

**Comment by jmprieur** [comment]
@shamiullahms
Did you add an Access token in the Authorization header?

Can you share the postman query you do? (repro steps I could use?)

**Comment by shamiullahms** [comment]
![Issue-01](https://user-images.githubusercontent.com/7916175/66502655-b76d5a80-ea93-11e9-9756-e7f2a5dcf689.JPG)
![Issue-02](https://user-images.githubusercontent.com/7916175/66502819-074c2180-ea94-11e9-9c6a-6aa14df046d5.JPG)

**Comment by shamiullahms** [comment]
[Issue-Postman.log](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore/files/3708554/Issue-Postman.log)

**Comment by jmprieur** [comment]
@shamiullahms : looking at your logs, you seem to have a network (or firewall?) issue. None of the requests from the Web API seem to go through?

**Comment by shamiullahms** [comment]
For the same App Registration (client id, secret, scope, token url) its working fine for .NET framework API, I only have this issue with .NET core API. I doubt any issue with firewall especially when I can connect using .NET Framework API

**Comment by jmprieur** [comment]
Can you please share a call stack for the exception in the Web API?

**Comment by shamiullahms** [comment]
Call stack is blank

**Comment by TiagoBrenck** [comment]
We are archiving this sample. Please refer to: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2
