### ISSUE TITLE
sample does not compile

### ISSUE THREAD

**Issue by GitHubSachin** [Azure-Samples/active-directory-dotnet-native-aspnet5#4]
Looks like lot of changes happened in ASP.net 5 and this sample is outdated, it does not compile with latest version of asp.net 5 on visual studio 2015 update 1
Is there plan to fix this? also do you know if OAuthBearer middleware is will be updated? I tried simple blank web api project and tried to add oauth bearer middleware nugget and that does not compile either.

**Comment by jmprieur** [comment]
PR #11 rmoves the sample to ASP.NET Core 2.0
