### ISSUE TITLE
Update Tutorial to use MSAL instead of ADAL (experimental)?

### ISSUE THREAD

**Issue by casaout** [Azure-Samples/active-directory-dotnet-native-aspnet5#8]
I am using the code produced by this tutorial in a productive project (and it works well). I recently was made aware of a change in the authentication library and that I should **migrate my project to use MSAL** instead of the experimental ADAL (Microsoft.Experimental.IdentityModel.Cients.ActiveDirectory, Version 4.0.209160138-alpha). 

However, I found very little information on how to migrate from ADAL to MSAL and I had hoped to avoid the big effort of finding out everything myself. In case it is really necessary to migrate to MSAL; is an update of this tutorial planned?

Or, is a public update to the non-prerelease branch of the ADAL library planned?

Thanks!

**Comment by jmprieur** [comment]
The sample uses ADAL (not ADAL experimental).
We'll provide another sample with MSAL when the V2 endpoint supports having a public client application calling a Web API. Also we'll provide migration guides for people who will want to move their application from the AAD V1 endpoint (with ADAL.Net) to the AAD V2 endpoint (with MSAL.Net)

**Comment by casaout** [comment]
Thanks @jmprieur for the update! I decided to not for the migration guide any longer and migrate by myself. Works fine so far. :) I Hope, MSAL goes out of experimental-mode soon.

**Comment by jmprieur** [comment]
Great @casaout : we're interested in understanding if you had issues doing the migration, and also if you prefer the MSAL object model more than ADAL's.

**Comment by casaout** [comment]
> issues doing the migration

It took me quite a while to find the right documentation/tutorial/code snippets for the job (I am using MIcrosoft Graph in a C#-WPF-app). I found many outdated samples, etc. As soon as I found a good example, the migration was done in 2hrs.

> prefer teh MSAL object model more than ADAL

I am not using too much of it anyway, but I found MSAL much easier to use, i.e. the time from idea to deploy is even faster. 

So to summarize, I think a migration guide would be useful as a starting point (as that's what I spent the most time with). And it always takes some time to understand if a resource I've found is using ADAL or MSAL...

Otherwise, great work and I am happy (again) with it :)
Do you have a schedule for when the AAD2 V2 endpoint will be available for WPF?
